// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Data.Migrations
{
    [DbContext(typeof(LabContext))]
    [Migration("20211202012626_createTableContatos")]
    partial class createTableContatos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Data.Models.AgendamentoModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("diaColeta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("motorista")
                        .HasColumnType("text");

                    b.Property<decimal>("pesoMax")
                        .HasColumnType("numeric");

                    b.Property<string>("placa")
                        .HasColumnType("text");

                    b.Property<int?>("solicitacaoId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("solicitacaoId");

                    b.ToTable("agendamentos");
                });

            modelBuilder.Entity("Data.Models.ContatoModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("assunto")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("mensagem")
                        .HasColumnType("text");

                    b.Property<string>("nome")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("contatos");
                });

            modelBuilder.Entity("Data.Models.SolicitacaoModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<decimal>("frete")
                        .HasColumnType("numeric");

                    b.Property<int>("nota")
                        .HasColumnType("integer");

                    b.Property<string>("ordemVenda")
                        .HasColumnType("text");

                    b.Property<DateTime>("prazoFim")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("prazoInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("solicitacaos");
                });

            modelBuilder.Entity("Data.Models.AgendamentoModel", b =>
                {
                    b.HasOne("Data.Models.SolicitacaoModel", "solicitacao")
                        .WithMany()
                        .HasForeignKey("solicitacaoId");

                    b.Navigation("solicitacao");
                });
#pragma warning restore 612, 618
        }
    }
}
